### ISSUE TITLE
Add filters to other endpoints

### ISSUE THREAD

**Issue by marcoslhc** [Code-for-Miami/restaurant-inspections-api#54]
Add filters to businesses and counties

it could be like
`http://45.55.191.140/businesses?zipCodes=32615`

Also the ability to query just one business: `http://45.55.191.140/businesses/:id` or `http://45.55.191.140/businesses/:slugged_name` and just one county: `http://45.55.191.140/county/:id`

This will make the queries easier and faster in the front end.

**Comment by teh0xqb** [comment]
I am working on businesses/id, although we don't return have a specific "id" field for businesses. the primary key/uniqueness comes from its license_number. Would the route `businesses/:id` where id is the license_number work?

I think that's a bit confusing (non-straightforward). I'll see if I modify the queries to return an `id` key for businesses (the id would basically match the license_number).

**Comment by marcoslhc** [comment]
Yes I saw that. 
we have two semantic related possibilities here:
- Take businesses away from the domain of this app, define License as the main entity related to inspections and rename the endpoint to `/licenses` and `/licenses/:id`
- Keep the business entity and define the `license_number` as the unique key of the entity
Any way, we remove confusion with documentation :)

**Comment by marcoslhc** [comment]
I was about to start doing it myself, but I'm still not confident enough hehehehehe

**Comment by teh0xqb** [comment]
> Anyway, we remove confusion with documentation

Will try to work on this.

**Comment by teh0xqb** [comment]
Lets not close this one until we add the filters/id for counties, and maybe add more filters for inspections? Probably after we take care of that other ticket where we'll reuse code better.

**Comment by teh0xqb** [comment]
@marcoslhc I just thought of something. Florida only has 67 Counties, which are already populated in the api/database. It won't grow bigger than that. I don't think any consumer would need to filter counties on the api level. They can always query all of them, and filter on their side. I would even say that they can cache the response (in memory?, or caching on a file / cdn) since it would make more sense to most consumers.

The *only* reason, I would say, an api consumer would need to query `/counties/:id` is to get the inspections count in a particular county.

What do you think?

I think we could close this one out and only reopen when it actually pops up (a client needs a county by id).

**Comment by marcoslhc** [comment]
Yup. I agree. Closing this until further notice as suggested :)
